[package]
name = "P4"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
lettre = "0.11.18"
rand = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
